print('hello world!')
print('The answer is ', 9 + 1, '.', sep='')
print('hi', 'there', sep='\n\n')
print('hi', end=' ')
print('brian')
f = open('hello.txt', 'w')
print('hi Zach', file=f)
ans = input('How are you?')
print('Glad you are ', ans, '.', sep='')
print('I\'m ok')
print('\\')
print(len(ans))
print(all((8>7, 6==6, 0<5)))
pet = 'cat'
print(pet.upper())
print(pet.replace('cat', 'dog'))
print(ord('j'))
